fs            = require 'fs'
{print}       = require 'util'
{spawn, exec} = require 'child_process'
watch         = require 'directory-tree-watcher'

node = null

stream = (command, options, callback) ->
  sub = spawn command, options
  sub.stdout.on 'data', (data) -> print data.toString()
  sub.stderr.on 'data', (data) -> print data.toString()
  sub.on 'exit', (status) -> callback?() if status is 0
  sub

dns = ->
  options = ['lib/dns_server.coffee']
  node = stream 'coffee', options

start = ->
  node?.kill()
  options = ['development.coffee']
  node = stream 'coffee', options

task 'run', 'Run server', ->
  dns()
  start()
  watch 'development.coffee', (event, file) ->
    start()
